// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnooojnfuxtlrwzsbpwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxub29vam5mdXh0bHJ3enNicHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzg3NjUsImV4cCI6MjA3MTY1NDc2NX0.eVx4bxWr9Twl3Dhw4XfmOl2C_uCM3O4dlrsSp5xpWHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});